// Badge definitions for the gamification system

export interface BadgeDefinition {
  id: string;
  name: string;
  description: string;
  icon: string;       // lucide icon name
  color: string;      // Badge color
  xpReward: number;   // XP earned when badge is unlocked
  category: 'learning' | 'social' | 'streak' | 'milestone' | 'simulator';
  condition: BadgeCondition;
}

export type BadgeCondition =
  | { type: 'quiz_count'; count: number }
  | { type: 'course_count'; count: number }
  | { type: 'lesson_count'; count: number }
  | { type: 'streak'; days: number }
  | { type: 'follower_count'; count: number }
  | { type: 'following_count'; count: number }
  | { type: 'first_action'; action: string }
  | { type: 'simulator_scenario'; scenarioId: string };

export const badges: BadgeDefinition[] = [
  // Learning badges
  {
    id: 'first_quiz',
    name: 'Quiz Initiate',
    description: 'Complete your first quiz',
    icon: 'Target',
    color: '#4CAF50',
    xpReward: 25,
    category: 'learning',
    condition: { type: 'quiz_count', count: 1 },
  },
  {
    id: 'quiz_enthusiast',
    name: 'Quiz Enthusiast',
    description: 'Complete 5 quizzes',
    icon: 'Crosshair',
    color: '#FF9800',
    xpReward: 50,
    category: 'learning',
    condition: { type: 'quiz_count', count: 5 },
  },
  {
    id: 'quiz_master',
    name: 'Quiz Master',
    description: 'Complete 10 quizzes',
    icon: 'Award',
    color: '#9C27B0',
    xpReward: 100,
    category: 'learning',
    condition: { type: 'quiz_count', count: 10 },
  },
  {
    id: 'first_course',
    name: 'Knowledge Seeker',
    description: 'Start your first course',
    icon: 'BookOpen',
    color: '#2196F3',
    xpReward: 25,
    category: 'learning',
    condition: { type: 'course_count', count: 1 },
  },
  {
    id: 'course_graduate',
    name: 'Course Graduate',
    description: 'Complete your first course',
    icon: 'GraduationCap',
    color: '#C9A961',
    xpReward: 100,
    category: 'learning',
    condition: { type: 'first_action', action: 'course_completed' },
  },
  {
    id: 'lesson_warrior',
    name: 'Lesson Warrior',
    description: 'Complete 10 lessons',
    icon: 'Swords',
    color: '#E91E63',
    xpReward: 75,
    category: 'learning',
    condition: { type: 'lesson_count', count: 10 },
  },

  // Streak badges
  {
    id: 'streak_starter',
    name: 'Streak Starter',
    description: 'Maintain a 3-day streak',
    icon: 'Flame',
    color: '#FF5722',
    xpReward: 30,
    category: 'streak',
    condition: { type: 'streak', days: 3 },
  },
  {
    id: 'week_warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: 'Flame',
    color: '#FF9800',
    xpReward: 75,
    category: 'streak',
    condition: { type: 'streak', days: 7 },
  },
  {
    id: 'fortnight_fighter',
    name: 'Fortnight Fighter',
    description: 'Maintain a 14-day streak',
    icon: 'Flame',
    color: '#F44336',
    xpReward: 150,
    category: 'streak',
    condition: { type: 'streak', days: 14 },
  },
  {
    id: 'monthly_master',
    name: 'Monthly Master',
    description: 'Maintain a 30-day streak',
    icon: 'Flame',
    color: '#E91E63',
    xpReward: 300,
    category: 'streak',
    condition: { type: 'streak', days: 30 },
  },

  // Social badges
  {
    id: 'social_butterfly',
    name: 'Social Butterfly',
    description: 'Follow 10 community members',
    icon: 'Users',
    color: '#3F51B5',
    xpReward: 50,
    category: 'social',
    condition: { type: 'following_count', count: 10 },
  },
  {
    id: 'rising_star',
    name: 'Rising Star',
    description: 'Gain 10 followers',
    icon: 'Star',
    color: '#FFC107',
    xpReward: 75,
    category: 'social',
    condition: { type: 'follower_count', count: 10 },
  },
  {
    id: 'influencer',
    name: 'Influencer',
    description: 'Gain 50 followers',
    icon: 'Crown',
    color: '#C9A961',
    xpReward: 200,
    category: 'social',
    condition: { type: 'follower_count', count: 50 },
  },

  // Milestone badges
  {
    id: 'newcomer',
    name: 'Newcomer',
    description: 'Join the community',
    icon: 'Sparkles',
    color: '#4CAF50',
    xpReward: 10,
    category: 'milestone',
    condition: { type: 'first_action', action: 'user_joined' },
  },
  {
    id: 'dedicated_learner',
    name: 'Dedicated Learner',
    description: 'Complete 25 lessons',
    icon: 'Brain',
    color: '#9C27B0',
    xpReward: 150,
    category: 'milestone',
    condition: { type: 'lesson_count', count: 25 },
  },

  // Simulator badges
  {
    id: 'love-bomb-survivor',
    name: 'Love Bomb Survivor',
    description: 'Successfully navigate "The Love Bomb" scenario',
    icon: 'ShieldCheck',
    color: '#E91E63',
    xpReward: 50,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'narcissist-trap' },
  },
  {
    id: 'healthy-detector',
    name: 'Green Flag Spotter',
    description: 'Learn to recognize healthy patterns',
    icon: 'Heart',
    color: '#4CAF50',
    xpReward: 50,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'healthy-connection' },
  },
  {
    id: 'avoidant-expert',
    name: 'Avoidant Expert',
    description: 'Master the hot-cold dance without losing yourself',
    icon: 'RefreshCw',
    color: '#2196F3',
    xpReward: 75,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'avoidant-dance' },
  },
  {
    id: 'reality-anchor',
    name: 'Reality Anchor',
    description: 'Escape the gaslighting fog with your sanity intact',
    icon: 'Anchor',
    color: '#9C27B0',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'gaslighter-escape' },
  },
  {
    id: 'corporate-survivor',
    name: 'Corporate Survivor',
    description: 'Navigate office politics without becoming a victim',
    icon: 'Briefcase',
    color: '#FF9800',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'power-play' },
  },
  {
    id: 'simulator-initiate',
    name: 'Simulator Initiate',
    description: 'Complete your first dating simulator scenario',
    icon: 'Gamepad2',
    color: '#C9A961',
    xpReward: 25,
    category: 'simulator',
    condition: { type: 'first_action', action: 'simulator_first_complete' },
  },
  {
    id: 'simulator-master',
    name: 'Pattern Master',
    description: 'Complete all dating simulator scenarios with good outcomes',
    icon: 'Trophy',
    color: '#FFD700',
    xpReward: 250,
    category: 'simulator',
    condition: { type: 'first_action', action: 'simulator_all_complete' },
  },

  // New tactical scenario badges
  {
    id: 'investment-ladder-climber',
    name: 'Investment Ladder Climber',
    description: 'Master the art of earning investment before commitment',
    icon: 'TrendingUp',
    color: '#C9A961',
    xpReward: 75,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'investment-test' },
  },
  {
    id: 'rotation-master',
    name: 'Rotation Master',
    description: 'Maintain options without losing your center',
    icon: 'RefreshCw',
    color: '#F59E0B',
    xpReward: 75,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'rotation-master' },
  },
  {
    id: 'family-diplomat',
    name: 'Family Diplomat',
    description: 'Navigate family dynamics without compromising yourself',
    icon: 'Users',
    color: '#7C3AED',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'family-introduction' },
  },
  {
    id: 'beige-escape-artist',
    name: 'Beige Escape Artist',
    description: 'Exit gracefully by becoming utterly forgettable',
    icon: 'EyeOff',
    color: '#64748B',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'beige-escape' },
  },
  {
    id: 'ghost-protocol',
    name: 'Ghost Protocol',
    description: 'Handle being ghosted without losing your power',
    icon: 'Ghost',
    color: '#6366F1',
    xpReward: 75,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-ghost' },
  },
  {
    id: 'empress-crowned',
    name: 'Empress Crowned',
    description: 'Secure commitment from a position of absolute power',
    icon: 'Crown',
    color: '#C9A961',
    xpReward: 150,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'empress-move' },
  },

  // Strategy-branching scenario badges
  {
    id: 'covert-detector',
    name: 'Covert Detector',
    description: 'See through the victim mask to the narcissist beneath',
    icon: 'Theater',
    color: '#8B5CF6',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'covert-narcissist' },
  },
  {
    id: 'crumb-crusher',
    name: 'Crumb Crusher',
    description: 'Refuse breadcrumbs and demand the whole loaf',
    icon: 'Cookie',
    color: '#F59E0B',
    xpReward: 75,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'breadcrumber' },
  },
  {
    id: 'wall-climber',
    name: 'Wall Climber',
    description: 'Navigate dismissive-avoidant walls without losing yourself',
    icon: 'ShieldOff',
    color: '#3B82F6',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'dismissive-avoidant' },
  },
  {
    id: 'promise-auditor',
    name: 'Promise Auditor',
    description: 'See through future-faking to demand present action',
    icon: 'Cloud',
    color: '#EC4899',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'future-faker' },
  },

  // Long-form modular scenario badges
  {
    id: 'social-fortress',
    name: 'Social Fortress',
    description: 'Survive high-stakes social events with grace',
    icon: 'Calendar',
    color: '#F472B6',
    xpReward: 150,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'wedding-weekend' },
  },
  {
    id: 'clean-cut',
    name: 'Clean Cut',
    description: 'Execute a perfect exit without drama or debris',
    icon: 'Scissors',
    color: '#10B981',
    xpReward: 125,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'clean-break' },
  },
  {
    id: 'first-date-survivor',
    name: 'First Date Survivor',
    description: 'Escape a nightmare date with your dignity intact',
    icon: 'AlertTriangle',
    color: '#EF4444',
    xpReward: 75,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'first-date-from-hell' },
  },

  // Power Plays scenario badges
  {
    id: 'interview-closer',
    name: 'Interview Closer',
    description: 'Command the room and secure the offer',
    icon: 'Briefcase',
    color: '#1E40AF',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-interview' },
  },
  {
    id: 'territory-mapper',
    name: 'Territory Mapper',
    description: 'Navigate your first 90 days like a strategic genius',
    icon: 'Map',
    color: '#10B981',
    xpReward: 125,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-first-90-days' },
  },
  {
    id: 'value-architect',
    name: 'Value Architect',
    description: 'Secure the raise you deserve through strategic framing',
    icon: 'TrendingUp',
    color: '#22C55E',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-raise-negotiation' },
  },
  {
    id: 'boss-tamer',
    name: 'Boss Tamer',
    description: 'Manage an impossible boss without losing your sanity',
    icon: 'UserX',
    color: '#DC2626',
    xpReward: 150,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-impossible-boss' },
  },
  {
    id: 'silent-surgeon',
    name: 'Silent Surgeon',
    description: 'Handle a problem employee with surgical precision',
    icon: 'UserMinus',
    color: '#F97316',
    xpReward: 125,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-problem-employee' },
  },
  {
    id: 'layoff-survivor',
    name: 'Layoff Survivor',
    description: 'Navigate restructuring and come out stronger',
    icon: 'Shield',
    color: '#7C3AED',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-layoff-lottery' },
  },
  {
    id: 'boardroom-sovereign',
    name: 'Boardroom Sovereign',
    description: 'Command executive attention with unshakeable presence',
    icon: 'Presentation',
    color: '#4F46E5',
    xpReward: 150,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-executive-presentation' },
  },
  {
    id: 'fortress-mind',
    name: 'Fortress Mind',
    description: 'Defend against hostile acquisition tactics',
    icon: 'Castle',
    color: '#B91C1C',
    xpReward: 200,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-hostile-offer' },
  },
  {
    id: 'inner-circle',
    name: 'Inner Circle',
    description: 'Navigate executive networking at the highest level',
    icon: 'Users',
    color: '#C9A961',
    xpReward: 200,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-ceo-dinner' },
  },
  {
    id: 'chaos-commander',
    name: 'Chaos Commander',
    description: 'Lead through crisis with unwavering composure',
    icon: 'Flame',
    color: '#DC2626',
    xpReward: 200,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-crisis' },
  },
  {
    id: 'credit-reclaimer',
    name: 'Credit Reclaimer',
    description: 'Expose the thief and reclaim your work',
    icon: 'Award',
    color: '#F59E0B',
    xpReward: 125,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'the-credit-thief' },
  },

  // Male variant scenario badges
  {
    id: 'male-ego-shield',
    name: 'Ego Shield',
    description: 'Deflect narcissistic manipulation targeting your status',
    icon: 'Shield',
    color: '#E91E63',
    xpReward: 50,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'male-narcissist-trap' },
  },
  {
    id: 'male-standard-bearer',
    name: 'Standard Bearer',
    description: 'Recognize and embrace healthy relationship patterns',
    icon: 'Flag',
    color: '#4CAF50',
    xpReward: 50,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'male-healthy-connection' },
  },
  {
    id: 'male-ice-walker',
    name: 'Ice Walker',
    description: 'Navigate avoidant patterns without losing frame',
    icon: 'Snowflake',
    color: '#2196F3',
    xpReward: 75,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'male-avoidant-dance' },
  },
  {
    id: 'male-truth-anchor',
    name: 'Truth Anchor',
    description: 'Stay grounded against reality-warping manipulation',
    icon: 'Anchor',
    color: '#9C27B0',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'male-gaslighter-escape' },
  },
  {
    id: 'male-suit-of-armor',
    name: 'Suit of Armor',
    description: 'Navigate corporate politics with strategic precision',
    icon: 'Briefcase',
    color: '#FF9800',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'male-power-play' },
  },
  {
    id: 'male-field-general',
    name: 'Field General',
    description: 'Maintain options while building genuine connections',
    icon: 'Swords',
    color: '#F59E0B',
    xpReward: 75,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'male-rotation-master' },
  },
  {
    id: 'male-shadow-king',
    name: 'Shadow King',
    description: 'Handle ghosting with unshakeable composure',
    icon: 'Ghost',
    color: '#6366F1',
    xpReward: 100,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'male-the-ghost' },
  },
  {
    id: 'male-crown-prince',
    name: 'Crown Prince',
    description: 'Secure commitment as the high-value prize',
    icon: 'Crown',
    color: '#C9A961',
    xpReward: 150,
    category: 'simulator',
    condition: { type: 'simulator_scenario', scenarioId: 'male-emperor-move' },
  },
];

// Get badge by ID
export function getBadgeById(id: string): BadgeDefinition | undefined {
  return badges.find(b => b.id === id);
}

// Get badges by category
export function getBadgesByCategory(category: BadgeDefinition['category']): BadgeDefinition[] {
  return badges.filter(b => b.category === category);
}
